import { DocArticle } from './types';

export const docArticles: DocArticle[] = [
  {
    slug: 'introduction',
    category: 'Introduction',
    title: 'What is Pigeon?',
    description: 'An overview of Pigeon Social, what it stands for, and how it brings communities, creators, and conversations together.',
    lastUpdated: '2026-08-10',
    sections: [
      { type: 'heading', level: 2, id: 'overview', title: 'Overview' },
      {
        type: 'paragraph',
        text: 'Pigeon Social is a next-generation social networking platform built around communities, conversations, creators, privacy, and meaningful connections. Instead of an endless, impersonal feed, Pigeon gives people dedicated spaces to gather, share ideas, and talk — with encryption, thoughtful moderation, and creator tools at the core.',
      },
      {
        type: 'paragraph',
        text: 'Whether you are a student organizing a study group, a creator building an audience, a business reaching customers, or someone who just wants to keep in touch with friends, Pigeon is designed to make online interaction feel purposeful again.',
      },
      { type: 'heading', level: 2, id: 'core-pillars', title: 'Core pillars' },
      {
        type: 'list',
        items: [
          'Communities — dedicated spaces for shared interests with their own rules, moderators, and culture.',
          'Conversations — posts, comments, reactions, polls, and end-to-end encrypted messaging.',
          'Creators — tools to publish, build an audience, get verified, and grow sustainably.',
          'Privacy — encryption, granular controls, and a privacy-first philosophy by default.',
          'Meaningful connections — an AI-powered For You feed designed around relevance, not outrage.',
        ],
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'New here?',
        text: 'Start with Creating your Pigeon account, then read Creating your first post to get moving quickly.',
      },
      { type: 'heading', level: 2, id: 'availability', title: 'Availability' },
      {
        type: 'paragraph',
        text: 'Pigeon is available on the web and on mobile apps. This documentation covers the core product behavior that is consistent across platforms; some UI details may differ slightly between devices.',
      },
    ],
    related: ['getting-started', 'creating-your-account', 'creating-your-first-post'],
  },
  {
    slug: 'getting-started',
    category: 'Getting Started',
    title: 'Getting started with Pigeon',
    description: 'A quick orientation to the Pigeon interface, core concepts, and your first steps on the platform.',
    lastUpdated: '2026-08-12',
    sections: [
      { type: 'heading', level: 2, id: 'welcome', title: 'Welcome to Pigeon' },
      {
        type: 'paragraph',
        text: 'This guide walks you through the essentials so you can go from a brand-new account to an active community member in minutes.',
      },
      { type: 'heading', level: 2, id: 'key-concepts', title: 'Key concepts' },
      {
        type: 'list',
        items: [
          'Your feed — a personalized stream of posts from people and communities you follow, powered by the For You algorithm.',
          'Communities — topic-based spaces with their own posts, rules, and moderators.',
          'Messaging — private, end-to-end encrypted conversations with individuals and small groups.',
          'Profile — your public identity on Pigeon, including your bio, posts, and verification status.',
        ],
      },
      { type: 'heading', level: 2, id: 'first-steps', title: 'Your first steps' },
      {
        type: 'steps',
        steps: [
          { title: 'Create your account', description: 'Sign up with an email address and choose a unique username.' },
          { title: 'Complete your profile', description: 'Add a photo, bio, and a few interests so Pigeon can recommend relevant communities.' },
          { title: 'Join a few communities', description: 'Communities are where conversation happens on Pigeon. Start with two or three.' },
          { title: 'Make your first post', description: 'Share a thought, a link, or a question to introduce yourself.' },
          { title: 'Turn on notifications', description: 'Decide what you want to be notified about so you stay in the loop without being overwhelmed.' },
        ],
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Explore the interface',
        text: 'The left sidebar on web gives you quick access to your feed, communities, messages, notifications, and profile. On mobile, these live in the bottom navigation bar.',
      },
    ],
    related: ['introduction', 'creating-your-account', 'creating-your-first-post', 'joining-communities'],
  },
  {
    slug: 'creating-your-account',
    category: 'Account',
    title: 'Creating your Pigeon account',
    description: 'How to sign up, verify your email, and set up a strong, secure account from day one.',
    lastUpdated: '2026-08-09',
    sections: [
      { type: 'heading', level: 2, id: 'sign-up', title: 'Signing up' },
      {
        type: 'paragraph',
        text: 'You can create a Pigeon account from the web app or the mobile app. You will need an email address and a password that you do not use anywhere else.',
      },
      {
        type: 'steps',
        steps: [
          { title: 'Open Pigeon', description: 'Go to pigeon.social or open the Pigeon app and tap Get Started.' },
          { title: 'Enter your details', description: 'Provide your email, a unique username, and a strong password.' },
          { title: 'Confirm your email', description: 'Check your inbox for a confirmation link and click it to activate your account.' },
          { title: 'Set up your profile', description: 'Add a profile photo, display name, and a short bio.' },
        ],
      },
      {
        type: 'callout',
        calloutType: 'warning',
        title: 'Choose a strong password',
        text: 'Use a long passphrase or a password manager. Pigeon supports two-factor authentication — turn it on as soon as your account is created.',
      },
      { type: 'heading', level: 2, id: 'username', title: 'Choosing a username' },
      {
        type: 'paragraph',
        text: 'Your username is your unique handle on Pigeon. It can be changed later, but frequent changes may confuse people who know you by a previous handle, so pick something durable.',
      },
      {
        type: 'info-box',
        title: 'Username rules',
        text: 'Usernames must be 3–20 characters, contain only letters, numbers, and underscores, and must not be already taken or reserved.',
      },
      { type: 'heading', level: 2, id: 'two-factor', title: 'Enabling two-factor authentication' },
      {
        type: 'paragraph',
        text: 'Two-factor authentication (2FA) adds a second layer of security to your account. Pigeon supports both authenticator apps and SMS codes. Authenticator apps are recommended.',
      },
    ],
    related: ['getting-started', 'account-security', 'privacy-and-security'],
  },
  {
    slug: 'creating-your-first-post',
    category: 'Posts',
    title: 'Creating your first post',
    description: 'Learn how posts work on Pigeon — text, media, polls, music, and the options available when you publish.',
    lastUpdated: '2026-08-08',
    sections: [
      { type: 'heading', level: 2, id: 'composing', title: 'Composing a post' },
      {
        type: 'paragraph',
        text: 'Posts are the primary way to share on Pigeon. A post can include text, images, a poll, a music attachment, or a voice post. You can post to your profile, to a community you are a member of, or both.',
      },
      { type: 'heading', level: 2, id: 'options', title: 'Post options' },
      {
        type: 'table',
        headers: ['Option', 'What it does'],
        rows: [
          ['Post to community', 'Shares the post inside a specific community space.'],
          ['Anonymous posting', 'Hides your identity from viewers while still being subject to moderation.'],
          ['Drafts', 'Save a post without publishing and come back to it later.'],
          ['Voice post', 'Record a short audio clip and attach it to your post.'],
          ['Music attachment', 'Attach a track so others can play it inline.'],
          ['Screenshot protection', 'Discourages screenshots on supported devices.'],
        ],
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Availability note',
        text: 'Voice posts, music attachments, and screenshot protection are rolling out gradually. Some may be marked as beta or planned in your region.',
      },
      { type: 'heading', level: 2, id: 'publishing', title: 'Publishing' },
      {
        type: 'paragraph',
        text: 'When you are ready, tap Post. Your post will appear in the feeds of people who follow you and, if you posted to a community, in that community\u2019s feed.',
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Save a draft',
        text: 'Not ready to post? Tap Save as draft. You can find your drafts under your profile and publish them whenever you like.',
      },
    ],
    related: ['posts-feature', 'drafts', 'live-polls', 'anonymous-posting'],
  },
  {
    slug: 'joining-communities',
    category: 'Communities',
    title: 'Joining communities',
    description: 'How to find, join, and participate in communities that match your interests.',
    lastUpdated: '2026-08-07',
    sections: [
      { type: 'heading', level: 2, id: 'discovering', title: 'Discovering communities' },
      {
        type: 'paragraph',
        text: 'Communities are where focused conversations happen on Pigeon. You can discover them through the Explore page, recommendations in your feed, or by searching for a topic directly.',
      },
      { type: 'heading', level: 2, id: 'joining', title: 'Joining a community' },
      {
        type: 'paragraph',
        text: 'Most communities are open — you can join instantly. Some communities require approval from a moderator, and a few are invite-only.',
      },
      {
        type: 'steps',
        steps: [
          { title: 'Find a community', description: 'Use Explore or search to locate a community by name or topic.' },
          { title: 'Read the rules', description: 'Every community has rules. Read them before posting to avoid having content removed.' },
          { title: 'Join', description: 'Tap Join. For approval-based communities, your request will be reviewed by a moderator.' },
          { title: 'Introduce yourself', description: 'Many communities have an introduction thread — a great place to start.' },
        ],
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Start small',
        text: 'Joining two or three active communities is usually more rewarding than joining dozens and losing track of them.',
      },
    ],
    related: ['creating-a-community', 'community-moderation', 'communities-feature'],
  },
  {
    slug: 'creating-a-community',
    category: 'Communities',
    title: 'Creating a community',
    description: 'Start your own community — set the topic, rules, and moderation style to shape the culture you want.',
    lastUpdated: '2026-08-06',
    sections: [
      { type: 'heading', level: 2, id: 'before-you-start', title: 'Before you start' },
      {
        type: 'paragraph',
        text: 'A good community has a clear topic, a welcoming tone, and a moderator willing to keep things healthy. Before creating one, ask yourself: is there already a community for this topic? Would people want to gather here regularly?',
      },
      { type: 'heading', level: 2, id: 'creating', title: 'Creating the community' },
      {
        type: 'steps',
        steps: [
          { title: 'Choose a name and handle', description: 'Pick a clear name and a unique community handle.' },
          { title: 'Write a description', description: 'Explain what the community is about and who it is for.' },
          { title: 'Set membership type', description: 'Choose open, approval-based, or invite-only.' },
          { title: 'Add rules', description: 'Write 3–6 clear rules that set the tone and expectations.' },
          { title: 'Add moderators', description: 'Invite trusted members to help you moderate as the community grows.' },
        ],
      },
      {
        type: 'callout',
        calloutType: 'warning',
        title: 'You are responsible for your community',
        text: 'As a community owner, you are expected to uphold Pigeon\u2019s community standards and respond to reports in a reasonable timeframe.',
      },
    ],
    related: ['joining-communities', 'community-moderation', 'communities-feature'],
  },
  {
    slug: 'sending-encrypted-messages',
    category: 'Messaging',
    title: 'Sending encrypted messages',
    description: 'How end-to-end encrypted messaging works on Pigeon and what it means for your privacy.',
    lastUpdated: '2026-08-05',
    sections: [
      { type: 'heading', level: 2, id: 'how-it-works', title: 'How encryption works' },
      {
        type: 'paragraph',
        text: 'Messages on Pigeon are end-to-end encrypted (E2EE). This means only you and the people you are messaging can read the content — not Pigeon, not anyone in between. Encryption keys are generated on your device and exchanged securely with your conversation partners.',
      },
      {
        type: 'info-box',
        title: 'What end-to-end encryption covers',
        text: 'Text, images, voice notes, files, and polls sent in private messages are all end-to-end encrypted. Metadata (such as who you message and when) is minimized but not eliminated.',
      },
      { type: 'heading', level: 2, id: 'starting', title: 'Starting a conversation' },
      {
        type: 'paragraph',
        text: 'To start an encrypted conversation, open Messages, tap New, and select a contact. You can message individuals or create small encrypted groups.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Safety number',
        text: 'For sensitive conversations, you can verify a safety number with your contact to confirm the encryption has not been tampered with. This is optional but recommended for journalists, activists, and high-risk users.',
      },
      { type: 'heading', level: 2, id: 'limitations', title: 'What encryption does not do' },
      {
        type: 'list',
        items: [
          'It does not protect you if your device is compromised.',
          'It does not hide the fact that you are messaging someone from Pigeon\u2019s servers.',
          'It does not prevent someone you message from screenshotting or copying the conversation.',
        ],
      },
    ],
    related: ['messaging-feature', 'privacy-and-security', 'message-encryption'],
  },
  {
    slug: 'managing-notifications',
    category: 'Notifications',
    title: 'Managing notifications',
    description: 'Control what you are notified about, how, and when — so Pigeon works for you instead of distracting you.',
    lastUpdated: '2026-08-04',
    sections: [
      { type: 'heading', level: 2, id: 'types', title: 'Notification types' },
      {
        type: 'list',
        items: [
          'Mentions — when someone tags you in a post or comment.',
          'Replies — when someone replies to your post or comment.',
          'Reactions — when someone reacts to your content.',
          'Community activity — new posts or pinned announcements in your communities.',
          'Messages — new encrypted messages.',
          'System — security alerts, verification updates, and policy notices.',
        ],
      },
      { type: 'heading', level: 2, id: 'controls', title: 'Controls' },
      {
        type: 'paragraph',
        text: 'You can toggle each notification type on or off, choose between push, email, or in-app delivery, and set quiet hours so you are not disturbed at certain times.',
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Reduce noise',
        text: 'If your feed feels overwhelming, turn off reactions and community activity notifications and keep only mentions, replies, and messages on.',
      },
    ],
    related: ['notifications-feature', 'account-settings'],
  },
  {
    slug: 'verification-badges',
    category: 'Verification',
    title: 'Pigeon Premium & Verification Badges',
    description: 'Understand what Pigeon Premium is, why you need it, the different verification badge categories, and what is required for each.',
    lastUpdated: '2026-08-21',
    sections: [
      { type: 'heading', level: 2, id: 'what-is-premium', title: 'What is Pigeon Premium & Verification?' },
      {
        type: 'paragraph',
        text: 'Pigeon Premium is an exclusive tier that grants you a Verification Badge along with premium features. A verification badge confirms that an account is authentic and notable. It builds trust, helps you stand out in the community, and provides advanced tools like algorithm priority and extended media uploads.',
      },
      { type: 'heading', level: 2, id: 'why-verify', title: 'Why Get Verified?' },
      {
        type: 'list',
        items: [
          'Build Trust — Prove to your audience that you are who you say you are.',
          'Algorithm Priority — Get increased reach for your posts in the For You feed.',
          'Premium Features — Access longer voice posts, larger file uploads, and custom profile accents.',
          'Stand Out — Your unique badge (Blue, Gold, or Gray) will be visible across all your posts and profile.',
        ],
      },
      { type: 'heading', level: 2, id: 'categories', title: 'Badge Categories & Subcategories' },
      {
        type: 'paragraph',
        text: 'Pigeon offers three distinct verification badge categories, tailored for different types of users. Each category requires specific documentation (subcategories) to prove authenticity.',
      },
      { type: 'heading', level: 3, id: 'blue-badge', title: '1. General / Creator (Blue Badge)' },
      {
        type: 'paragraph',
        text: 'For individual creators, influencers, celebrities, and public figures.',
      },
      {
        type: 'list',
        items: [
          'Personal Details: Full name, username, DOB, and bio.',
          'Identity Proof: NID or Passport Upload.',
          'Face Scan: Live face verification for security.',
          'Payment: Choose Weekly, Monthly, Yearly, or Lifetime premium subscription.',
        ],
      },
      { type: 'heading', level: 3, id: 'gold-badge', title: '2. Business / Corporate (Gold Badge)' },
      {
        type: 'paragraph',
        text: 'For brands, startups, organizations, and corporate entities looking to build official presence.',
      },
      {
        type: 'list',
        items: [
          'Personal Details: Representative\'s information.',
          'Business Info: Trade License, TIN Certificate, and Company Registration.',
          'Face Scan: Representative\'s live face verification.',
          'Payment: Choose Weekly, Monthly, Yearly, or Lifetime premium subscription.',
        ],
      },
      { type: 'heading', level: 3, id: 'gray-badge', title: '3. Government / Official (Gray Badge)' },
      {
        type: 'paragraph',
        text: 'For government agencies, public officials, state institutions, and authorized media personnel.',
      },
      {
        type: 'list',
        items: [
          'Personal Details: Official representative\'s information.',
          'Gov Credentials: Government ID Card and Official Authorization Letter.',
          'Face Scan: Representative\'s live face verification.',
          'Payment: Choose Weekly, Monthly, Yearly, or Lifetime premium subscription.',
        ],
      },
      { type: 'heading', level: 2, id: 'applying', title: 'How to Apply' },
      {
        type: 'paragraph',
        text: 'You can apply directly from the app by going to Settings → Pigeon Verified. Select your category, upload the required documents in the subcategories, and complete your subscription payment.',
      },
    ],
    related: ['creator-features', 'pigeon-premium'],
  },
  {
    slug: 'pigeon-premium',
    category: 'Premium',
    title: 'Pigeon Premium',
    description: 'An overview of Premium, what it includes, and how it differs from the free experience.',
    lastUpdated: '2026-08-02',
    sections: [
      { type: 'heading', level: 2, id: 'what-is-premium', title: 'What is Pigeon Premium?' },
      {
        type: 'paragraph',
        text: 'Pigeon Premium is an optional subscription that unlocks advanced tools for creators and power users, supports Pigeon\u2019s development, and keeps the platform ad-free for everyone.',
      },
      { type: 'heading', level: 2, id: 'included', title: 'What is included' },
      {
        type: 'list',
        items: [
          'Algorithm priority — increased reach for your most meaningful posts.',
          'Extended media — longer voice posts, larger file uploads, and higher-resolution media.',
          'Advanced analytics — deeper insight into your audience and post performance.',
          'Custom profile accents — premium themes and a premium badge.',
          'Drafts history — access to older drafts and scheduled posts.',
          'Priority support — faster response from Pigeon support.',
        ],
      },
      {
        type: 'callout',
        calloutType: 'note',
        title: 'Premium does not buy moderation leniency',
        text: 'Premium subscribers are held to the same community standards as everyone else. Subscribing does not exempt you from rules.',
      },
      { type: 'heading', level: 2, id: 'pricing', title: 'Pricing and plans' },
      {
        type: 'paragraph',
        text: 'Premium is available as a monthly or annual subscription. Annual plans offer a discount. See the in-app Premium page for current pricing in your region.',
      },
    ],
    related: ['algorithm-priority', 'creator-features', 'verification-badges'],
  },
  {
    slug: 'privacy-and-security',
    category: 'Privacy & Security',
    title: 'Privacy and security',
    description: 'A plain-language overview of how Pigeon protects your data, your conversations, and your account.',
    lastUpdated: '2026-08-01',
    sections: [
      { type: 'heading', level: 2, id: 'philosophy', title: 'Our philosophy' },
      {
        type: 'paragraph',
        text: 'Pigeon is built on the idea that people should control their own information. We collect what we need to make the product work, encrypt what we can, and give you tools to manage what others see about you.',
      },
      { type: 'heading', level: 2, id: 'account-security', title: 'Account security' },
      {
        type: 'list',
        items: [
          'Use a strong, unique password.',
          'Enable two-factor authentication.',
          'Review active sessions regularly and log out of devices you no longer use.',
          'Be cautious of phishing — Pigeon will never ask for your password by email or message.',
        ],
      },
      { type: 'heading', level: 2, id: 'data', title: 'Your data' },
      {
        type: 'paragraph',
        text: 'You can download a copy of your data at any time from Settings \u2192 Privacy \u2192 Export data. You can delete your account and associated data from the same section.',
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Review your privacy settings',
        text: 'Spend five minutes in Settings \u2192 Privacy to decide who can see your posts, who can message you, and whether your profile is indexed by search engines.',
      },
    ],
    related: ['account-security', 'message-encryption', 'sending-encrypted-messages'],
  },
  {
    slug: 'for-you-feed',
    category: 'Feed',
    title: 'Understanding the For You feed',
    description: 'How the AI-powered For You feed works, what signals it uses, and how to customize what you see.',
    lastUpdated: '2026-08-14',
    sections: [
      { type: 'heading', level: 2, id: 'overview', title: 'Overview' },
      {
        type: 'paragraph',
        text: 'The For You feed is Pigeon\u2019s default feed, powered by a recommendation model that surfaces posts relevant to your interests. Unlike engagement-driven feeds on other platforms, For You is designed around relevance and meaning, not outrage.',
      },
      { type: 'heading', level: 2, id: 'how-it-works', title: 'How it works' },
      {
        type: 'paragraph',
        text: 'The feed ranks posts based on several signals: your interactions (reactions, replies, saves), the communities you are active in, the creators you follow, and topical relevance. Posts are scored and presented in a personalized order.',
      },
      {
        type: 'table',
        headers: ['Signal', 'What it means'],
        rows: [
          ['Interactions', 'Posts you react to, reply to, or save influence what you see more of.'],
          ['Community activity', 'Posts from communities you are active in rank higher.'],
          ['Recency', 'Newer posts get a boost, but relevance matters more than timestamp.'],
          ['Diversity', 'The feed avoids showing too many posts from the same source.'],
          ['Muted topics', 'Posts matching muted topics are filtered out entirely.'],
        ],
      },
      { type: 'heading', level: 2, id: 'controls', title: 'Customizing your feed' },
      {
        type: 'steps',
        steps: [
          { title: 'Switch to chronological', description: 'If you prefer a time-ordered feed, tap the feed toggle and select Chronological.' },
          { title: 'Mute topics and accounts', description: 'Mute specific topics, accounts, or communities to remove them from your feed.' },
          { title: 'Adjust signal weight', description: 'Fine-tune how much weight recency vs. relevance gets in the For You ranking.' },
          { title: 'Reset signals', description: 'If recommendations feel stale, reset your feed signals to start fresh.' },
        ],
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Feed feeling noisy?',
        text: 'Mute a few topics and leave two or three active communities. A smaller, more relevant set of signals produces a calmer feed.',
      },
      { type: 'heading', level: 2, id: 'transparency', title: 'Transparency' },
      {
        type: 'paragraph',
        text: 'Pigeon shows you which signals are influencing your feed in Settings \u2192 Feed. You can see which communities and topics are weighted highest and adjust them directly.',
      },
    ],
    related: ['introduction', 'creating-your-first-post', 'search-and-discovery'],
  },
  {
    slug: 'account-settings',
    category: 'Account',
    title: 'Account settings',
    description: 'Manage your profile, preferences, security, and privacy from one centralized settings hub.',
    lastUpdated: '2026-08-13',
    sections: [
      { type: 'heading', level: 2, id: 'overview', title: 'Settings overview' },
      {
        type: 'paragraph',
        text: 'Account settings on Pigeon are organized into sections: Profile, Security, Privacy, Notifications, Feed, and Verification. You can access them from Settings in the left sidebar or the gear icon on your profile.',
      },
      { type: 'heading', level: 2, id: 'profile', title: 'Profile settings' },
      {
        type: 'list',
        items: [
          'Display name \u2014 the name shown on your profile and posts.',
          'Username \u2014 your unique handle. Can be changed, but not too frequently.',
          'Bio \u2014 a short description of yourself, up to 160 characters.',
          'Profile photo and header \u2014 visual identity on your profile.',
          'Interests \u2014 tags that help Pigeon recommend relevant communities.',
        ],
      },
      { type: 'heading', level: 2, id: 'security', title: 'Security settings' },
      {
        type: 'list',
        items: [
          'Password \u2014 change your password regularly.',
          'Two-factor authentication \u2014 enable 2FA with an authenticator app or SMS.',
          'Active sessions \u2014 see which devices are logged in and revoke any you do not recognize.',
          'Login alerts \u2014 get notified when someone logs in from a new device.',
        ],
      },
      { type: 'heading', level: 2, id: 'privacy', title: 'Privacy settings' },
      {
        type: 'table',
        headers: ['Setting', 'Options'],
        rows: [
          ['Who can see your posts', 'Everyone / Followers only / Community members'],
          ['Who can message you', 'Everyone / Followers / No one'],
          ['Who can tag you', 'Everyone / Followers / No one'],
          ['Profile indexing', 'Allow / disallow search engine indexing'],
          ['Blocked accounts', 'View and manage your blocked list'],
        ],
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Review regularly',
        text: 'We recommend reviewing your privacy and security settings every few months, especially after major product updates.',
      },
      { type: 'heading', level: 2, id: 'data', title: 'Data and export' },
      {
        type: 'paragraph',
        text: 'From Settings \u2192 Privacy you can export a copy of your data, including your posts, messages metadata, and profile information. Account deletion is also available here.',
      },
    ],
    related: ['creating-your-account', 'managing-notifications', 'privacy-and-security'],
  },
  {
    slug: 'live-polls',
    category: 'Content',
    title: 'Creating live polls',
    description: 'How to create polls in posts and communities, configure options, and read live results.',
    lastUpdated: '2026-08-11',
    sections: [
      { type: 'heading', level: 2, id: 'overview', title: 'Overview' },
      {
        type: 'paragraph',
        text: 'Live polls let you gather opinions in real time. You can create a poll in any post, whether on your profile or in a community. Polls are great for quick decisions, casual questions, and community feedback.',
      },
      { type: 'heading', level: 2, id: 'creating', title: 'Creating a poll' },
      {
        type: 'steps',
        steps: [
          { title: 'Open the composer', description: 'Start a new post as you normally would.' },
          { title: 'Add a poll', description: 'Tap the poll icon in the composer toolbar.' },
          { title: 'Write your question', description: 'Enter a clear, concise question for your poll.' },
          { title: 'Add options', description: 'Add between 2 and 6 answer options. Each option can be up to 50 characters.' },
          { title: 'Set duration', description: 'Choose how long the poll runs \u2014 from 1 hour to 7 days.' },
          { title: 'Publish', description: 'Post to your profile or a community. Results update live as people vote.' },
        ],
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Poll best practices',
        text: 'Keep options distinct and mutually exclusive. Avoid overlapping choices that make it hard for voters to decide.',
      },
      { type: 'heading', level: 2, id: 'results', title: 'Viewing results' },
      {
        type: 'paragraph',
        text: 'Poll results are visible to everyone who can see the post. You see the percentage for each option and the total vote count. After the poll ends, the final results remain visible on the post.',
      },
      {
        type: 'info-box',
        title: 'Poll limits',
        text: '2\u20136 options per poll \u00b7 50 characters per option \u00b7 1 hour to 7 days duration \u00b7 One vote per user \u00b7 Votes are anonymous',
      },
    ],
    related: ['creating-your-first-post', 'posts-feature', 'communities-feature'],
  },
  {
    slug: 'music-attachments',
    category: 'Content',
    title: 'Music attachments',
    description: 'Attach music tracks to your posts so people can play them inline while they read.',
    lastUpdated: '2026-08-10',
    sections: [
      { type: 'heading', level: 2, id: 'overview', title: 'Overview' },
      {
        type: 'paragraph',
        text: 'Music attachments let you attach a track to any post. People who see the post can play the track inline without leaving Pigeon. This is a beta feature and may change as it develops.',
      },
      {
        type: 'callout',
        calloutType: 'warning',
        title: 'Beta feature',
        text: 'Music attachments are in beta. Availability, supported sources, and upload limits may change. Some features may not be available in all regions.',
      },
      { type: 'heading', level: 2, id: 'attaching', title: 'Attaching music' },
      {
        type: 'steps',
        steps: [
          { title: 'Open the composer', description: 'Start a new post.' },
          { title: 'Tap the music icon', description: 'Select the music attachment option in the composer toolbar.' },
          { title: 'Link or upload', description: 'Paste a link to a supported track, or upload an audio file from your device.' },
          { title: 'Add context', description: 'Write a caption or description for your post.' },
          { title: 'Publish', description: 'Your post will display a now-playing bar with inline playback.' },
        ],
      },
      { type: 'heading', level: 2, id: 'playback', title: 'Inline playback' },
      {
        type: 'paragraph',
        text: 'When someone encounters your post, they see a music bar with play/pause, a progress indicator, and the track title. Tapping play starts inline playback without navigating away.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Supported sources',
        text: 'During beta, we support links from major music platforms and direct file uploads (MP3, M4A, WAV up to 15 MB). More sources will be added as the feature matures.',
      },
    ],
    related: ['creating-your-first-post', 'voice-posts', 'posts-feature'],
  },
  {
    slug: 'search-and-discovery',
    category: 'Content',
    title: 'Search and discovery',
    description: 'Find posts, communities, people, and trending topics on Pigeon using search and explore.',
    lastUpdated: '2026-08-09',
    sections: [
      { type: 'heading', level: 2, id: 'search', title: 'Searching on Pigeon' },
      {
        type: 'paragraph',
        text: 'Pigeon search lets you find posts, communities, people, and topics. The search bar is available at the top of the app on web and in the navigation on mobile.',
      },
      {
        type: 'steps',
        steps: [
          { title: 'Open search', description: 'Tap the search bar or press Ctrl+K (Cmd+K on Mac).' },
          { title: 'Enter your query', description: 'Type what you are looking for \u2014 a topic, a community name, a username, or keywords.' },
          { title: 'Filter results', description: 'Use tabs to filter by Posts, Communities, People, or Topics.' },
          { title: 'Open a result', description: 'Tap any result to view the full post, community, or profile.' },
        ],
      },
      { type: 'heading', level: 2, id: 'explore', title: 'Explore page' },
      {
        type: 'paragraph',
        text: 'The Explore page surfaces trending topics, recommended communities, and popular posts. It is a great way to discover new content and communities outside your existing network.',
      },
      {
        type: 'list',
        items: [
          'Trending topics \u2014 see what people are talking about right now.',
          'Recommended communities \u2014 communities Pigeon thinks you might like based on your interests.',
          'Popular posts \u2014 high-engagement posts from across the platform.',
          'New communities \u2014 recently created communities looking for members.',
        ],
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Find your niche',
        text: 'Use Explore to find communities for your specific interests. Joining two or three active communities is the fastest way to make Pigeon feel like home.',
      },
      { type: 'heading', level: 2, id: 'trending', title: 'Trending topics' },
      {
        type: 'paragraph',
        text: 'Trending topics are ranked by a spam-resistant algorithm that considers the velocity and diversity of participation, not just raw volume. This makes it harder for coordinated groups to manipulate what trends.',
      },
    ],
    related: ['for-you-feed', 'joining-communities', 'trending-topics'],
  },
  {
    slug: 'creator-features',
    category: 'Creators',
    title: 'Creator tools',
    description: 'Analytics, scheduling, verification, and audience insights \u2014 everything creators need to grow on Pigeon.',
    lastUpdated: '2026-08-08',
    sections: [
      { type: 'heading', level: 2, id: 'overview', title: 'Creator tools overview' },
      {
        type: 'paragraph',
        text: 'Pigeon provides a suite of creator tools available to everyone, with extended features for Premium subscribers. These tools help you understand your audience, plan content, and grow sustainably.',
      },
      { type: 'heading', level: 2, id: 'analytics', title: 'Audience analytics' },
      {
        type: 'paragraph',
        text: 'Analytics show you how your posts perform, who your audience is, and what content resonates. Free accounts see basic metrics; Premium unlocks deeper insights.',
      },
      {
        type: 'table',
        headers: ['Metric', 'Free', 'Premium'],
        rows: [
          ['Post impressions', 'Yes', 'Yes'],
          ['Reactions and replies', 'Yes', 'Yes'],
          ['Follower growth', 'Summary', 'Detailed timeline'],
          ['Audience demographics', 'No', 'Yes'],
          ['Best posting times', 'No', 'Yes'],
          ['Community reach breakdown', 'No', 'Yes'],
        ],
      },
      { type: 'heading', level: 2, id: 'scheduling', title: 'Post scheduling (Premium)' },
      {
        type: 'paragraph',
        text: 'Premium subscribers can schedule posts to publish at a future time. This is useful for creators who want to maintain a consistent posting cadence across time zones.',
      },
      {
        type: 'steps',
        steps: [
          { title: 'Compose your post', description: 'Write your post as usual.' },
          { title: 'Choose schedule', description: 'Instead of Post, tap Schedule and pick a date and time.' },
          { title: 'Confirm', description: 'Your post is saved as a scheduled draft and will publish automatically.' },
          { title: 'Manage scheduled posts', description: 'View, edit, or cancel scheduled posts from your drafts.' },
        ],
      },
      { type: 'heading', level: 2, id: 'highlight-pins', title: 'Highlight pins' },
      {
        type: 'paragraph',
        text: 'You can pin up to three posts to the top of your profile. Use this to highlight your best work, important announcements, or an introduction post.',
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Growing on Pigeon',
        text: 'Post consistently to your profile and relevant communities, engage with replies, and use analytics to understand what resonates. Communities are the fastest path to an audience on Pigeon.',
      },
    ],
    related: ['verification-badges', 'pigeon-premium', 'for-you-feed'],
  },
  {
    slug: 'community-moderation',
    category: 'Communities',
    title: 'Community moderation',
    description: 'Tools and best practices for moderating your community, handling reports, and keeping conversations healthy.',
    lastUpdated: '2026-08-07',
    sections: [
      { type: 'heading', level: 2, id: 'overview', title: 'Moderation overview' },
      {
        type: 'paragraph',
        text: 'As a community owner or moderator, you have tools to keep your community healthy: a moderation queue, member management, pinned posts, thread locking, and content removal.',
      },
      { type: 'heading', level: 2, id: 'mod-queue', title: 'Moderation queue' },
      {
        type: 'paragraph',
        text: 'The moderation queue collects reported content from your community in one place. You can review each report, see the reason, and take action \u2014 remove the content, warn the user, or dismiss the report.',
      },
      {
        type: 'steps',
        steps: [
          { title: 'Open the queue', description: 'Go to your community and tap the moderation icon.' },
          { title: 'Review reports', description: 'Each report shows the content, the reporter\u2019s reason, and the user\u2019s history.' },
          { title: 'Take action', description: 'Remove content, issue a warning, or dismiss if no violation occurred.' },
          { title: 'Follow up', description: 'For repeated violations, consider removing the user from the community.' },
        ],
      },
      { type: 'heading', level: 2, id: 'tools', title: 'Moderation tools' },
      {
        type: 'table',
        headers: ['Tool', 'What it does'],
        rows: [
          ['Remove post', 'Deletes a post from the community feed.'],
          ['Lock thread', 'Prevents new replies on a post while keeping it visible.'],
          ['Pin post', 'Pins a post to the top of the community feed. Up to 3 pins.'],
          ['Remove member', 'Removes a user from the community. They can rejoin if open.'],
          ['Ban member', 'Permanently bans a user from rejoining the community.'],
          ['Assign moderator', 'Gives another member moderation powers.'],
        ],
      },
      {
        type: 'callout',
        calloutType: 'warning',
        title: 'Act on reports promptly',
        text: 'Community moderators are expected to act on reports in a reasonable timeframe. Persistent inaction may result in Pigeon stepping in to enforce platform standards.',
      },
      { type: 'heading', level: 2, id: 'best-practices', title: 'Best practices' },
      {
        type: 'list',
        items: [
          'Write clear, specific rules \u2014 vague rules lead to inconsistent enforcement.',
          'Be consistent \u2014 apply rules equally to all members, including friends.',
          'Communicate actions \u2014 when you remove content, the poster gets a notification with the reason.',
          'Escalate to Pigeon \u2014 for serious violations (threats, illegal content), report to Pigeon in addition to community action.',
          'Recruit help \u2014 as your community grows, add trusted members as moderators.',
        ],
      },
    ],
    related: ['creating-a-community', 'joining-communities', 'privacy-and-security'],
  },
  {
    slug: 'troubleshooting',
    category: 'Help',
    title: 'Troubleshooting',
    description: 'Solutions to common issues with Pigeon \u2014 login problems, missing notifications, feed issues, and more.',
    lastUpdated: '2026-08-15',
    sections: [
      { type: 'heading', level: 2, id: 'login', title: 'Login issues' },
      {
        type: 'paragraph',
        text: 'If you cannot log in, try the following steps in order. Most login issues are resolved by the first or second step.',
      },
      {
        type: 'steps',
        steps: [
          { title: 'Check your credentials', description: 'Make sure your email and password are correct. Use the password reset link if needed.' },
          { title: 'Clear cache', description: 'Clear your browser cache or app data and try again.' },
          { title: 'Check 2FA', description: 'If you have 2FA enabled, make sure your authenticator app is synced. Use backup codes if your device is lost.' },
          { title: 'Contact support', description: 'If nothing works, contact Pigeon support from the help page.' },
        ],
      },
      { type: 'heading', level: 2, id: 'notifications', title: 'Missing notifications' },
      {
        type: 'paragraph',
        text: 'If you are not receiving notifications, check the following:',
      },
      {
        type: 'list',
        items: [
          'Check Settings \u2192 Notifications \u2014 make sure the relevant notification types are enabled.',
          'Check your device settings \u2014 ensure Pigeon has permission to send push notifications.',
          'Check quiet hours \u2014 if quiet hours are active, notifications are paused.',
          'Check your email spam folder \u2014 email notifications may be filtered.',
        ],
      },
      { type: 'heading', level: 2, id: 'feed', title: 'Feed issues' },
      {
        type: 'paragraph',
        text: 'If your feed feels stale, empty, or full of irrelevant content:',
      },
      {
        type: 'list',
        items: [
          'Reset feed signals in Settings \u2192 Feed \u2192 Reset signals.',
          'Join a few active communities to give the feed more to work with.',
          'Mute topics or accounts that are flooding your feed.',
          'Switch to chronological view to see if the issue is with ranking.',
        ],
      },
      { type: 'heading', level: 2, id: 'messaging', title: 'Messaging issues' },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Messages not delivering?',
        text: 'If your encrypted messages are not delivering, make sure both you and your contact have a stable internet connection. Messages are delivered when both devices are online. If issues persist, verify your safety numbers.',
      },
      { type: 'heading', level: 2, id: 'performance', title: 'App performance' },
      {
        type: 'list',
        items: [
          'Clear the app cache from Settings \u2192 Storage.',
          'Update to the latest version of Pigeon.',
          'Restart the app or refresh the page.',
          'If the app is slow on mobile, try switching to a lighter view in Settings.',
        ],
      },
      {
        type: 'callout',
        calloutType: 'tip',
        title: 'Still stuck?',
        text: 'Contact Pigeon support from Settings \u2192 Help. Premium subscribers get priority support with faster response times.',
      },
    ],
    related: ['managing-notifications', 'for-you-feed', 'sending-encrypted-messages', 'account-settings'],
  },
  {
    slug: 'keyboard-shortcuts',
    category: 'Help',
    title: 'Keyboard shortcuts',
    description: 'Navigate Pigeon faster with keyboard shortcuts on the web app.',
    lastUpdated: '2026-08-12',
    sections: [
      { type: 'heading', level: 2, id: 'overview', title: 'Overview' },
      {
        type: 'paragraph',
        text: 'Pigeon on the web supports keyboard shortcuts for common actions. These work on Chrome, Firefox, Safari, and Edge.',
      },
      { type: 'heading', level: 2, id: 'navigation', title: 'Navigation' },
      {
        type: 'table',
        headers: ['Shortcut', 'Action'],
        rows: [
          ['Ctrl+K / Cmd+K', 'Open search'],
          ['Ctrl+/ / Cmd+/', 'Open search (alternative)'],
          ['G then H', 'Go to home feed'],
          ['G then C', 'Go to communities'],
          ['G then M', 'Go to messages'],
          ['G then N', 'Go to notifications'],
          ['G then P', 'Go to profile'],
          ['Esc', 'Close dialog or search'],
        ],
      },
      { type: 'heading', level: 2, id: 'actions', title: 'Actions' },
      {
        type: 'table',
        headers: ['Shortcut', 'Action'],
        rows: [
          ['N', 'New post'],
          ['J / K', 'Move down / up in feed'],
          ['L', 'React to current post'],
          ['R', 'Reply to current post'],
          ['S', 'Save current post'],
          ['Shift+?', 'Show keyboard shortcuts help'],
        ],
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Shortcut help',
        text: 'Press Shift+? anywhere in the Pigeon web app to see a full list of keyboard shortcuts. You can also find this in Settings \u2192 Keyboard shortcuts.',
      },
    ],
    related: ['getting-started', 'search-and-discovery'],
  },
];
