import { FeatureItem } from './types';

export const features: FeatureItem[] = [
  {
    slug: 'for-you-feed',
    name: 'AI-powered For You feed',
    icon: 'Sparkles',
    tagline: 'A relevance-first feed, not an outrage engine.',
    description:
      'The For You feed uses a recommendation model trained to surface posts that matter to you — from communities and creators you care about — without prioritizing controversy.',
    status: 'available',
    category: 'Feed',
    highlights: [
      'Personalized ranking across posts, communities, and creators.',
      'Adjustable signal controls — tune how much weight you give recency vs. relevance.',
      'Transparent controls for what influences your feed.',
    ],
    details: [
      { type: 'heading', level: 2, id: 'how-it-works', title: 'How the Algorithm Works' },
      {
        type: 'paragraph',
        text: 'The For You feed ranks posts dynamically based on your interactions, the communities you are active in, and positive signals like reactions and deep replies. Unlike traditional feeds, we do not boost posts that receive angry reactions or high report rates, preventing outrage-bait from dominating your screen.',
      },
      { type: 'heading', level: 3, id: 'customizing-signals', title: 'Customizing Your Signals' },
      {
        type: 'paragraph',
        text: 'You have complete control over your feed. Through your feed settings, you can adjust the balance of recency (chronological order) and AI relevance. This ensures that you can always switch back to a purely chronological feed whenever you want a raw time-based view.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Complete User Control',
        text: 'You can mute specific topics, keywords, accounts, or communities. If the recommendations start feeling repetitive or stale, you can reset your recommendation signals with a single click in your settings.',
      },
    ],
    related: ['trending-topics', 'posts-feature'],
  },
  {
    slug: 'posts-feature',
    name: 'Posts',
    icon: 'FileText',
    tagline: 'Share ideas, media, polls, and more.',
    description: 'Posts are the foundation of Pigeon — text, images, polls, music, and voice, with options for anonymity and drafts.',
    status: 'available',
    category: 'Content',
    highlights: [
      'Rich media: text, images, polls, music, and voice.',
      'Post to your profile, a community, or both.',
      'Anonymous posting and drafts supported.',
    ],
    details: [
      { type: 'heading', level: 2, id: 'composing', title: 'Composing a Post' },
      {
        type: 'paragraph',
        text: 'Creating a post on Pigeon is intuitive. Using the rich media composer, you can draft structured text, attach multiple high-resolution images, set up live interactive polls, attach your favorite music tracks, or record a quick audio voice post.',
      },
      { type: 'heading', level: 3, id: 'publishing-options', title: 'Flexible Publishing Options' },
      {
        type: 'paragraph',
        text: 'You can choose to publish posts to your public profile (followers feed) or directly to a community. If you want to write something sensitive, you can toggle the anonymity switch to publish without sharing your username.',
      },
    ],
    related: ['drafts', 'live-polls', 'voice-posts'],
  },
  {
    slug: 'comments',
    name: 'Comments',
    icon: 'MessageSquare',
    tagline: 'Threaded conversations under every post.',
    description: 'Comments support threading, reactions, and moderation, so discussions stay organized and readable.',
    status: 'available',
    category: 'Content',
    highlights: ['Threaded replies', 'Reactions on comments', 'Moderator controls'],
    details: [
      { type: 'heading', level: 2, id: 'threading-details', title: 'Threaded Conversation Architecture' },
      {
        type: 'paragraph',
        text: 'To keep conversations readable, Pigeon groups replies into nested branches. This allows multiple side-conversations to develop naturally under a single post without cluttering the main comments view.',
      },
      { type: 'heading', level: 3, id: 'collapsible-replies', title: 'Collapsible Threads' },
      {
        type: 'paragraph',
        text: 'Visitors can collapse or expand comment threads with a simple tap. If a reply is off-topic, community moderators can hide it or flag it, maintaining discussion quality.',
      },
    ],
    related: ['posts-feature', 'reactions'],
  },
  {
    slug: 'reactions',
    name: 'Reactions',
    icon: 'Heart',
    tagline: 'Express more than a like.',
    description: 'A small, considered set of reactions designed to convey meaning without gamifying engagement.',
    status: 'available',
    category: 'Content',
    highlights: ['Curated reaction set', 'No engagement-bait counts', 'Per-post reaction visibility controls'],
    details: [
      { type: 'heading', level: 2, id: 'meaningful-reactions', title: 'Meaningful Reactions' },
      {
        type: 'paragraph',
        text: 'Pigeon provides a handpicked selection of reactions (Like, Love, Clap, Support, and Insightful). This curated set ensures users can show meaningful feedback without resorting to toxic engagement metrics.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'No Popularity Contest',
        text: 'Reaction counts are displayed cleanly without flashing notification counters, preventing popularity contests and keeping the focus on actual discussion content.',
      },
    ],
    related: ['posts-feature', 'comments'],
  },
  {
    slug: 'communities-feature',
    name: 'Communities',
    icon: 'Users',
    tagline: 'Dedicated spaces for shared interests.',
    description: 'Create or join communities with their own rules, moderators, culture, and feed.',
    status: 'available',
    category: 'Community',
    highlights: ['Open, approval, or invite-only membership', 'Community rules and moderation tools', 'Dedicated feed and pinned posts'],
    details: [
      { type: 'heading', level: 2, id: 'community-moderation', title: 'Ownership & Moderation Tools' },
      {
        type: 'paragraph',
        text: 'Every community is led by its creator and designated moderators. Administrators have full authority to delete posts, ban abusive users, pin announcements, and custom-tailor the rules to match their community guidelines.',
      },
      { type: 'heading', level: 3, id: 'membership-levels', title: 'Flexible Membership Modes' },
      {
        type: 'paragraph',
        text: 'Communities can be configured in three modes: Public (open to everyone), Approved (membership requires moderator review), or Private (invite-only space).',
      },
    ],
    related: ['joining-communities', 'community-moderation'],
  },
  {
    slug: 'live-polls',
    name: 'Live Polls',
    icon: 'Vote',
    tagline: 'Gather opinions in real time.',
    description: 'Create polls in posts or communities with live results and configurable duration and options.',
    status: 'available',
    category: 'Content',
    highlights: ['Up to 6 options', 'Configurable duration', 'Live-updating results'],
    details: [
      { type: 'heading', level: 2, id: 'creating-polls', title: 'Setting Up Polls' },
      {
        type: 'paragraph',
        text: 'You can create dynamic polls directly within the composer. Add up to 6 custom voting options, set the poll duration (ranging from 1 day to 1 week), and publish. Results update in real-time as users cast their votes.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Completely Anonymous Voting',
        text: 'To protect user privacy, individual votes are encrypted and anonymous. Nobody (not even community moderators or admins) can see who voted for which option.',
      },
    ],
    related: ['posts-feature', 'communities-feature'],
  },
  {
    slug: 'messaging-feature',
    name: 'End-to-End Encrypted Messaging',
    icon: 'Lock',
    tagline: 'Private conversations that stay private.',
    description: 'All messages on Pigeon are end-to-end encrypted — only you and your conversation partners can read them.',
    status: 'available',
    category: 'Messaging',
    highlights: ['End-to-end encryption by default', 'Safety number verification', 'Encrypted group messaging'],
    details: [
      { type: 'heading', level: 2, id: 'encryption-architecture', title: 'Zero-Knowledge Security' },
      {
        type: 'paragraph',
        text: 'Pigeon uses industry-standard X25519 and AES-GCM encryption algorithms to secure chat messages. All encryption and decryption keys are generated and stored locally on your device. Pigeon servers act strictly as blind relays and cannot inspect, decrypt, or log your chat content.',
      },
      { type: 'heading', level: 3, id: 'safety-numbers', title: 'Safety Number Verification' },
      {
        type: 'paragraph',
        text: 'For sensitive communication, users can compare unique Safety Numbers (public key fingerprint fingerprints) with their contacts to verify that no man-in-the-middle attack has occurred.',
      },
    ],
    related: ['screenshot-protection'],
  },
  {
    slug: 'music-attachments',
    name: 'Music Attachments',
    icon: 'Music',
    tagline: 'Attach a track to any post.',
    description: 'Attach music to posts so people can play it inline while they read or scroll.',
    status: 'available',
    category: 'Content',
    highlights: ['Inline playback', 'Link or upload a track', 'Now playing indicator'],
    details: [
      { type: 'heading', level: 2, id: 'attaching-tracks', title: 'Adding Music to Your Posts' },
      {
        type: 'paragraph',
        text: 'Bring your posts to life by attaching audio tracks. You can search the built-in library, link external streaming tracks, or upload your own files. Users scrolling past your post can listen to the audio inline with a single tap.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Background Playback',
        text: 'The music player is built into the bottom of the app, allowing users to keep listening to the track even as they browse other screens or read comments.',
      },
    ],
    related: ['posts-feature', 'voice-posts'],
  },
  {
    slug: 'drafts',
    name: 'Drafts',
    icon: 'PenLine',
    tagline: 'Write now, publish later.',
    description: 'Save posts as drafts and come back to them. Premium includes draft history and scheduling.',
    status: 'available',
    category: 'Content',
    highlights: ['Auto-saved drafts', 'Premium: scheduled posts', 'Premium: draft history'],
    details: [
      { type: 'heading', level: 2, id: 'draft-autosave', title: 'Local & Cloud Auto-Save' },
      {
        type: 'paragraph',
        text: 'Never lose your thoughts. While writing a post, the composer automatically saves your text locally. You can close the app and reopen it later to continue exactly where you left off.',
      },
      { type: 'heading', level: 3, id: 'scheduling-drafts', title: 'Post Scheduling' },
      {
        type: 'paragraph',
        text: 'For power users and creators, Premium allows syncing drafts across all your devices and scheduling posts to publish automatically at a future time.',
      },
    ],
    related: ['posts-feature', 'premium-feature'],
  },
  {
    slug: 'notifications-feature',
    name: 'Notifications',
    icon: 'Bell',
    tagline: 'Stay in the loop, your way.',
    description: 'Granular notification controls across push, email, and in-app delivery, plus quiet hours.',
    status: 'available',
    category: 'Account',
    highlights: ['Per-type controls', 'Push, email, and in-app delivery', 'Quiet hours'],
    details: [
      { type: 'heading', level: 2, id: 'granular-controls', title: 'Granular Notification Settings' },
      {
        type: 'paragraph',
        text: 'Pigeon gives you complete mastery over your notifications. You can toggle push and email notifications individually for likes, comments, retweets, and private messages, keeping your notifications feed distraction-free.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Quiet Hours Mode',
        text: 'Enable Quiet Hours to automatically silence all push notifications during work hours or sleep, helping you maintain a healthy digital balance.',
      },
    ],
    related: ['account-settings'],
  },
  {
    slug: 'trending-topics',
    name: 'Trending Topics',
    icon: 'TrendingUp',
    tagline: 'See what the platform is talking about.',
    description: 'A curated, spam-resistant trending view that surfaces genuinely active topics across communities.',
    status: 'available',
    category: 'Discovery',
    highlights: ['Spam-resistant ranking', 'Personalized and global views', 'Topic pages'],
    details: [
      { type: 'heading', level: 2, id: 'spam-resistant-algorithm', title: 'Spam-Resistant Trending' },
      {
        type: 'paragraph',
        text: 'Pigeon\'s trending algorithm is built to resist coordinated manipulation. Instead of simply measuring the raw volume of posts, it factors in the diversity of participating users and communities, ensuring that genuine conversations rise to the top.',
      },
      { type: 'heading', level: 3, id: 'explore-trends', title: 'Trending Search Hub' },
      {
        type: 'paragraph',
        text: 'Explore popular trends and hashtags through the Explore screen. Clicking any trending topic takes you to a dedicated search page highlighting top posts, recent discussions, and active communities talking about it.',
      },
    ],
    related: ['for-you-feed'],
  },
  {
    slug: 'creator-features',
    name: 'Creator Features',
    icon: 'Sparkle',
    tagline: 'Tools to build and sustain an audience.',
    description: 'Analytics, audience insights, scheduling, and creator verification — the essentials for growing on Pigeon.',
    status: 'available',
    category: 'Creators',
    highlights: ['Audience analytics', 'Post scheduling (Premium)', 'Creator verification', 'Highlight pins'],
    details: [
      { type: 'heading', level: 2, id: 'creator-dashboard', title: 'Audience Insights Dashboard' },
      {
        type: 'paragraph',
        text: 'Grow your audience with analytics. The creator dashboard provides valuable statistics on post views, follower growth rates, post saves, share counts, and audience demographics.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Pinning Highlights',
        text: 'Showcase your best work. As a creator, you can pin your top posts to the top of your profile feed, allowing new visitors to instantly see your best content.',
      },
    ],
    related: ['verification-badges-feature', 'premium-feature'],
  },
  {
    slug: 'verification-badges-feature',
    name: 'Verification Badges',
    icon: 'BadgeCheck',
    tagline: 'Authenticity, not endorsement.',
    description: 'Three badge types confirm that notable accounts are who they say they are.',
    status: 'available',
    category: 'Verification',
    highlights: ['Creator, organization, and individual badges', 'Free to apply', 'Clear criteria'],
    details: [
      { type: 'heading', level: 2, id: 'verification-tiers', title: 'Three Tiers of Trust' },
      {
        type: 'paragraph',
        text: 'Pigeon utilizes three distinct verification badges to prove authenticity: Blue Badge for individual creators/celebrities, Gold Badge for verified businesses and organizations, and Gray Badge for government departments and public representatives.',
      },
      { type: 'heading', level: 3, id: 'application-process', title: 'Applying for Verification' },
      {
        type: 'paragraph',
        text: 'Verification is free and open to all notable figures who meet the verification criteria. Once verified, creators also unlock access to monetizing their profile via subscriber-only posts.',
      },
    ],
    related: ['creator-features', 'premium-feature'],
  },
  {
    slug: 'premium-feature',
    name: 'Premium',
    icon: 'Crown',
    tagline: 'Advanced tools that support the platform.',
    description: 'An optional subscription with algorithm priority, extended media, advanced analytics, and more.',
    status: 'available',
    category: 'Subscription',
    highlights: ['Algorithm priority', 'Extended media limits', 'Advanced analytics', 'Priority support'],
    details: [
      { type: 'heading', level: 2, id: 'premium-benefits', title: 'Elevate Your Experience' },
      {
        type: 'paragraph',
        text: 'Pigeon Premium is a paid tier that unlocks advanced capabilities. Premium members receive algorithm priority (reach boost on quality posts), the ability to upload longer audio and high-res video files, advanced analytics, custom application themes, and priority support.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Supporting an Ad-Free App',
        text: 'Subscribing to Premium directly supports Pigeon, keeping the platform ad-free and tracking-free for everyone.',
      },
    ],
    related: ['algorithm-priority', 'creator-features'],
  },
  {
    slug: 'anonymous-posting',
    name: 'Anonymous Posting',
    icon: 'EyeOff',
    tagline: 'Share without attaching your identity.',
    description: 'Post anonymously in supported communities — your identity is hidden from viewers while still being known to moderators.',
    status: 'available',
    category: 'Privacy',
    highlights: ['Identity hidden from viewers', 'Still subject to moderation', 'Community-controlled'],
    details: [
      { type: 'heading', level: 2, id: 'anonymity-safety', title: 'Anonymity with Accountability' },
      {
        type: 'paragraph',
        text: 'Pigeon allows anonymous posting in participating communities. This helps users discuss sensitive issues, share feedback, or ask personal questions without fear of social repercussions.',
      },
      {
        type: 'callout',
        calloutType: 'warning',
        title: 'Anonymity is Not Impunity',
        text: 'To prevent harassment, anonymous posts are still monitored. In the event of a platform rule violation, moderators can see the author\'s account profile to take moderation action.',
      },
    ],
    related: ['posts-feature', 'messaging-feature'],
  },
  {
    slug: 'voice-posts',
    name: 'Voice Posts',
    icon: 'Mic',
    tagline: 'Record and share short audio.',
    description: 'Attach a short voice recording to a post to add tone and personality.',
    status: 'available',
    category: 'Content',
    highlights: ['Short audio clips', 'Inline playback', 'Transcription (planned)'],
    details: [
      { type: 'heading', level: 2, id: 'audio-composer', title: 'Share Your Voice' },
      {
        type: 'paragraph',
        text: 'Voice posts let you convey your tone, expression, and emotion directly. Tap the microphone icon in the composer, record up to 3 minutes of high-quality audio, and attach it to your post. Users can listen to the audio inline with clean wave-visuals.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Automated Transcription',
        text: 'We are working on integrating automated transcriptions, which will generate accurate text subtitles for voice posts, making them accessible to everyone.',
      },
    ],
    related: ['posts-feature', 'music-attachments'],
  },
  {
    slug: 'screenshot-protection',
    name: 'Screenshot Protection',
    icon: 'ShieldAlert',
    tagline: 'Discourage capturing sensitive content.',
    description: 'On supported devices, screenshot protection discourages capturing ephemeral or sensitive content.',
    status: 'available',
    category: 'Privacy',
    highlights: ['Discourages screenshots on supported devices', 'Notifies on capture where supported', 'Respects platform limits'],
    details: [
      { type: 'heading', level: 2, id: 'screenshot-prevention', title: 'Active Screenshot Prevention' },
      {
        type: 'paragraph',
        text: 'Pigeon integrates native operating system screenshot protection. On Android and iOS devices, this prevents users from taking screenshots or screen-recordings of chat screens, profiles, or private media threads, protecting your privacy.',
      },
      {
        type: 'callout',
        calloutType: 'warning',
        title: 'A Deterrent, Not a Guarantee',
        text: 'While screenshot protection blocks native capture options, it cannot prevent physical captures (like taking a photo of the screen with another camera). Use caution when sharing highly confidential information.',
      },
    ],
    related: ['messaging-feature'],
  },
  {
    slug: 'algorithm-priority',
    name: 'Algorithm Priority',
    icon: 'Gauge',
    tagline: 'Premium reach boost for meaningful posts.',
    description: 'Premium subscribers get increased reach on their highest-quality posts, with quality signals factored in.',
    status: 'available',
    category: 'Premium',
    highlights: ['Reach boost on top posts', 'Quality-weighted', 'Premium only'],
    details: [
      { type: 'heading', level: 2, id: 'quality-prioritization', title: 'Boost to Quality Engagement' },
      {
        type: 'paragraph',
        text: 'Pigeon Premium members get an organic reach multiplier on their posts. This multiplier helps your content find interested readers faster, ensuring your posts gain visibility organically.',
      },
      {
        type: 'callout',
        calloutType: 'info',
        title: 'Quality First',
        text: 'To avoid spam, the priority system only boosts posts that meet quality guidelines and receive constructive engagement, keeping the feed readable for everyone.',
      },
    ],
    related: ['premium-feature', 'for-you-feed', 'creator-features'],
  },
];
